#!/bin/bash

CC="gcc"
EXTRA=""
DEBUG=0
STATIC=0

usage() {
    echo "[=°-°=]: usage: $0 [--compiler || -cc gcc] [--extra \"extra cc tags\"] [--static] [--debug] [-o output] [--help | -h] file1.c file2.c ..."
    exit 1
}

if [[ $# -eq 0 ]]; then
    echo "[=°x°=]: no arguments provided"
    usage
fi

FILES=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --compiler) CC="$2"; shift 2 ;;
        -cc) CC="$2"; shift 2 ;;
        --extra) EXTRA="$2"; shift 2 ;;
        --debug) DEBUG=1; shift ;;
        -o) OUTPUT_NAME="$2"; shift 2 ;;
        --version) buxu --version; exit 0 ;;
        -v) buxu -v; exit 0 ;;
        --help) usage ;;
        -h) usage ;;
        --static) STATIC=1; shift ;;
        *) FILES="$FILES $1"
        shift ;;
    esac
done;

if [[ $FILES == "" ]]; then
    echo "[=°x°=]: no files provided"
    exit 1
fi

if [[ $DEBUG -eq 1 ]]; then
    DEBUGARGS="-g"
    echo "[=°-°=]: debug mode enabled"
else
    DEBUGARGS=""
fi

if [[ -z $OUTPUT_NAME ]]; then
    OUTPUT_NAME="a.out"
fi

if [[ $STATIC -eq 1 ]]; then
    echo "[=°-°=]: static mode enabled"
    echo "[=°-°=]: $CC $FILES -o $OUTPUT_NAME -c -O3 $EXTRA $DEBUGARGS"
    $CC $FILES -o $OUTPUT_NAME -c -O3 $EXTRA $DEBUGARGS
else
    echo "[=°-°=]: $CC $FILES -o $OUTPUT_NAME -shared -fPIC -O3 $EXTRA $DEBUGARGS -Wl,-rpath=$INSTALL_PATH/lib"
    $CC $FILES -o $OUTPUT_NAME -shared -fPIC -O3 $EXTRA $DEBUGARGS -Wl,-rpath=$INSTALL_PATH/lib
fi

echo "[=°-°=]: $OUTPUT_NAME" has been compiled.
