#!/bin/bash

CC="gcc"
EXTRA=""
DEBUG=0

usage() {
    echo "[=°-°=]: usage: $0 [--compiler || -cc gcc] [--extra \"extra cc tags\"] [--debug] [-o output] [--help | -h] file1.c file2.c ..."
    exit 1
}

if [[ $# -eq 0 ]]; then
    echo "[=°x°=]: no arguments provided"
    usage
fi

FILES=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --compiler) CC="$2"; shift 2 ;;
        -cc) CC="$2"; shift 2 ;;
        --extra) EXTRA="$2"; shift 2 ;;
        --debug) DEBUG=1; shift ;;
        -o) OUTPUT_NAME="$2"; shift 2 ;;
        --version) buxu --version; exit 0 ;;
        -v) buxu -v; exit 0 ;;
        --help) usage ;;
        -h) usage ;;
        *) if [[ ${1:0:1} != "-" ]]; then
            FILES="$FILES $1"
        fi
        shift ;;
    esac
done;

if [[ $FILES == "" ]]; then
    echo "[=°x°=]: no files provided"
    exit 1
fi

if [[ $DEBUG -eq 1 ]]; then
    DEBUGARGS="-g"
    echo "[=°-°=]: debug mode enabled"
else
    DEBUGARGS=""
fi
if [[ -z $OUTPUT_NAME ]]; then
    OUTPUT_NAME="a.out"
fi

echo "[=°-°=]: $CC $FILES -o $OUTPUT_NAME -shared -fPIC -O3 -lm -lbruter $EXTRA $DEBUGARGS -Wl,-rpath=$INSTALL_PATH/lib"
$CC $FILES -o $OUTPUT_NAME -shared -fPIC -O3 -lm -lbruter $EXTRA $DEBUGARGS -Wl,-rpath=$INSTALL_PATH/lib
echo "[=°-°=]: $OUTPUT_NAME" has been compiled.
