#!/bin/bash

# if /usr/share/buhl.js

if [ -f /usr/share/buhl.js ]; then
    node /usr/share/buhl.js "$1" > "$2"
else
    # check if buhl.js is in the current directory
    if [ -f ./buhl.js ]; then
        node ./buhl.js "$1" > "$2"
    else
        echo "Error: /usr/share/buhl.js or ./buhl.js not found."
        exit 1
    fi
fi