#!/bin/bash

# if /usr/share/buxuhl.js

if [ -f /usr/share/buxuhl.js ]; then
    # Check if the file is a valid JavaScript file
    if grep -q "function" /usr/share/buxuhl.js; then
        # Execute the JavaScript file using Node.js
        node /usr/share/buxuhl.js "$@"
    else
        echo "Error: /usr/share/buxuhl.js is not a valid JavaScript file."
        exit 1
    fi
else
    # check if buxuhl.js is in the current directory
    if [ -f ./buxuhl.js ]; then
        # Check if the file is a valid JavaScript file
        if grep -q "function" ./buxuhl.js; then
            # Execute the JavaScript file using Node.js
            node ./buxuhl.js "$@"
        else
            echo "Error: ./buxuhl.js is not a valid JavaScript file."
            exit 1
        fi
    else
        echo "Error: /usr/share/buxuhl.js or ./buxuhl.js not found."
        exit 1
    fi
fi

node 